export const Config = {
  //DELAY WILL BE RANDOMIZE BETWEEN MIN AND MAX
  DELAYMININMINUTES: 60,
  DELAYMAXINMINUTES: 120,

  //TRANSACTION AMOUNT WILL BE RANDOMIZE BETWEEN MIN AND MAX
  TXAMOUNTMIN: 0.0000001,
  TXAMOUNTMAX: 0.000001,

  //TRANSFER TO YOUR OWN ADDRESS
  USESELFTRANSFER: true,
  SELFTRANSFERCOUNT: 99,

  //TRANSFER TO ADDRESS ON THIS LIST
  USEFRIENDTRANSFER: false,
  FRIENDTRANSFERLIST: [
    "0x3fe6A02AB20dE8bf34fEFc106D72D7094C8C4404",
    "0x94C442D21bA584C0562Ab5CAcc8Efd633eC89470",
  ],

  //SWAP TOKEN
  USESWAP: true,
  SWAPCOUNT: 99,

  //ADD LIQUIDITY
  USEADDLIQUIDITY: true,
  ADDLIQUIDITYCOUNT: 99,

  //NOTE : Every count is daily based
  //so when you already reach the count, bot will run on continues cooldown until next day and daily count reset.
};
